# Generated by Django 3.2.20 on 2023-07-05 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('followers', '0001_initial'),
    ]

    operations = [
    ]
